steps:
 
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/my-ecp-backend",'-f', './Backend/myecp-backend/Dockerfile', '.' ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/my-ecp-backend"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "my-ecp-backend",
        "--image",
        "gcr.io/$PROJECT_ID/my-ecp-backend",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "8080"
      ]
  
options:
  logging: CLOUD_LOGGING_ONLY
